Fix unit test failure - txpackage_tests/package_submission_tests
Follow-on to commit 314d98599f16a7322197e330791e75aeb034f6cd that made
bad-witness-nonstandard rejection more specific; one of the test cases
needs to have its error expectation updated accordingly. Without the
patch:

$ test_bitcoin --run_test=txpackage_tests/package_submission_tests
test/txpackage_tests.cpp(303): error: in "txpackage_tests/package_submission_tests": check it_parent->second.m_state.GetRejectReason() == "bad-witness-nonstandard" has failed [bad-witness-nonwitness-input != bad-witness-nonstandard]